# config.yaml

# Don't change these
defaults:
  min_vibe_strength: 20
  max_vibe_strength: 100
  min_vibe_time: 0.5
  max_vibe_time: 20.0
  vibe_strength_divider: 1.5
  vibe_time_divider: 25
  min_vibe_score: 10
  intiface_ip: "ws://127.0.0.1:12345"

config:
  # Minimum and maximum vibration strengths, in percent
  min_vibe_strength: 20
  max_vibe_strength: 100

  # Minimum and maximum vibration times, in seconds
  min_vibe_time: 0.5
  max_vibe_time: 20.0

  # If the divider is 1.5, 150 points = 100% vibe strength
  vibe_strength_divider: 1.5

  # If the divider is 25, 25 points = 1 second of vibes
  vibe_time_divider: 25

  # Minimum score to vibrate at all
  min_vibe_score: 10

  # Don't change this unless you know what you're doing
  intiface_ip: "ws://127.0.0.1:12345"